_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: b8c380f7-4ccd-4a6c-bf4d-fb2a0c835ee5
name: 'Employee Portal'
mail: sandip.poddar@innoraft.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/6
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
